apiVersion: v1
kind: Namespace
metadata:
  name: mdas
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mynginx
  name: mynginx
  namespace: mdas
spec:
  containers:
  - image: nginx
    name: mynginx
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
  namespace: mdas
spec:
  ports:
  - nodePort: 32161
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mynginx
  type: NodePort